### ISSUE TITLE
1.3 installation error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JustLoy77/ebookdroid#118]
```
I attempted to install 1.3 but got the message "Installation error / Unknown 
reason -18".

```

Original issue reported on code.google.com by `danielar...@gmail.com` on 11 Jan 2012 at 5:00

**Comment by GoogleCodeExporter** [comment]
```
From market or from here ?
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 11 Jan 2012 at 5:02

**Comment by GoogleCodeExporter** [comment]
```
From the Market I get "Installation error / Unknown reason -18" and from here I 
get "Application not installed". Note: I'm using a rooted Sony prs-t1 that 
doesn't run all apps, but the previous version of Ebookdroid worked fine.
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
Can you provide information from android logs.
For collect log use any application from Market. Keyword for search logcat.
```

Original comment by `mc.creat` on 11 Jan 2012 at 5:14

**Comment by GoogleCodeExporter** [comment]
```
I hope this is what you asked for:

--------- beginning of /dev/log/system
W/InputManagerService( 2105): Window already focused, ignoring focus gain of: 
com.android.internal.view.IInputMethodClient$Stub$Proxy@3246fb08
--------- beginning of /dev/log/main
E/GTalkService( 2270): [ERROR: GTalkConnection.10] xmppError = null 
Authentication timed out.
W/KeyCharacterMap( 6012): No keyboard for id 0
W/KeyCharacterMap( 6012): Using default keymap: 
/system/usr/keychars/qwerty.kcm.bin
E/vending ( 6012): [1] GTalkServiceHelper.requestSendHeartbeat(): 
IllegalStateException using service connection
E/BroadcastReceiver( 6012): BroadcastReceiver trying to return result during a 
non-ordered broadcast
E/BroadcastReceiver( 6012): java.lang.RuntimeException: BroadcastReceiver 
trying to return result during a non-ordered broadcast
E/BroadcastReceiver( 6012):     at 
android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:45
1)
E/BroadcastReceiver( 6012):     at 
android.content.BroadcastReceiver.setResultCode(BroadcastReceiver.java:237)
E/BroadcastReceiver( 6012):     at 
com.android.vending.util.ServiceBroadcastReceiver.onReceive(ServiceBroadcastRece
iver.java:42)
E/BroadcastReceiver( 6012):     at 
android.app.ActivityThread.handleReceiver(ActivityThread.java:2810)
E/BroadcastReceiver( 6012):     at 
android.app.ActivityThread.access$3200(ActivityThread.java:125)
E/BroadcastReceiver( 6012):     at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
E/BroadcastReceiver( 6012):     at 
android.os.Handler.dispatchMessage(Handler.java:99)
E/BroadcastReceiver( 6012):     at android.os.Looper.loop(Looper.java:123)
E/BroadcastReceiver( 6012):     at 
android.app.ActivityThread.main(ActivityThread.java:4627)
E/BroadcastReceiver( 6012):     at java.lang.reflect.Method.invokeNative(Native 
Method)
E/BroadcastReceiver( 6012):     at java.lang.reflect.Method.invoke(Method.java:521)
E/BroadcastReceiver( 6012):     at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/BroadcastReceiver( 6012):     at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/BroadcastReceiver( 6012):     at dalvik.system.NativeStart.main(Native Method)
E/PackageHelper( 6250): Failed to create secure container smdl2tmp1
E/DefContainer( 6250): Failed to create container smdl2tmp1
W/InputManagerService( 2105): Window already focused, ignoring focus gain of: 
com.android.internal.view.IInputMethodClient$Stub$Proxy@323d0cf0


```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 5:32

**Comment by GoogleCodeExporter** [comment]
```
[ERROR: GTalkConnection.10] xmppError = null Authentication timed out.

means that google service were unstable at than moment.

Try to install from market again or download and install .apk manually.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 11 Jan 2012 at 6:43

**Comment by GoogleCodeExporter** [comment]
```
I've tried manually, and get the error "Application not installed" which I 
assume is related to these lines: 
E/PackageHelper( 6250): Failed to create secure container smdl2tmp1
E/DefContainer( 6250): Failed to create container smdl2tmp1
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 6:48

**Comment by GoogleCodeExporter** [comment]
```
Do you have free place (~6MB) on device ?
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 11 Jan 2012 at 7:05
- Changed state: **Discussion**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
The "SD card & phone storage settings" says I have 16.32MB of available space 
in internal phone storage.
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 7:13

**Comment by GoogleCodeExporter** [comment]
```
The problem is probably related to the fact that the previous version of 
Ebookdroid came pre-installed with the ooting package for the Sony prs-t1.
See: http://www.the-ebook.org/forum/viewtopic.php?t=21458
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
I've seen that error during upload to emulator .
It would be enough to delete old smdl2tmp1.asec file from /mnt/asec folder.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 11 Jan 2012 at 7:30

**Comment by GoogleCodeExporter** [comment]
```
http://forum.cyanogenmod.com/topic/3903-apps-wont-reinstall/page__view__findpost
__p__35232
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 11 Jan 2012 at 7:31

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
There is no /mnt/asec folder. A search for smdl2tmp1.asec gives no results.
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
This may be possible only under root privileges.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 11 Jan 2012 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
The creator of the root package writes:

"I am afraid eBookDroid can only be installed via direct copying into /data/app 
and /data/data/lib directories.  See how it's done in the install packages."
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
here is the procedure to install it on the prs-t1:

1. Uninstall Ebookdroid 1.2.2
2. Extract the 1.3 apk package and set aside the file 
lib/armeabi/libebookdroid.so.
3. Create the folder /data/data/org.ebookdroid/lib
4. Copy libebookdroid.so to /data/data/org.ebookdroid/lib
5. Copy the original .apk file to /data/app
6. Reboot the device
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 8:51

**Comment by GoogleCodeExporter** [comment]
```
Been impressed.
Can you add here a link to the topic with solution?
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 11 Jan 2012 at 9:01

**Comment by GoogleCodeExporter** [comment]
```
There is no link, I discovered the procedure myself.
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 9:09

**Comment by GoogleCodeExporter** [comment]
```
I am disappointed to see that the hardware page turn buttons of the prs-t1 do 
nothing in 1.3. I had hoped the developers would add this feature.
```

Original comment by `danielar...@gmail.com` on 11 Jan 2012 at 9:10

**Comment by GoogleCodeExporter** [comment]
```
Installation issue was caused by not-genuine version of ebookdroid from that 
firmware. That version has invalid digital signature and not supported by us. 
Possibly it can has some malware inside.
```

Original comment by `Andrei.K...@gmail.com` on 11 Jan 2012 at 9:36
- Changed state: **Invalid**
