### ISSUE TITLE
not open this file "GFT_Inferno_03.cbr"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JustLoy77/ebookdroid#221]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output?
not open this file "GFT_Inferno_03.cbr"
(Like all of the series)

What do you see instead?
white list with a page number


What version of the product are you using?
1.4.1

On what operating system?
2.3.5

What device are you using?
HTC Desire HD

Please provide any additional information below.

```

Original issue reported on code.google.com by `ed.v.he...@gmail.com` on 1 May 2012 at 2:31

Attachments:
- [Grimm_Fairy_Tales_Inferno_003_TriStan.cbr](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-0/Grimm_Fairy_Tales_Inferno_003_TriStan.cbr)

**Comment by GoogleCodeExporter** [comment]
```
На Asus TF201 открывает нормально. Правда, 
базовым вариантом - без оптимизаций.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 1 May 2012 at 5:04
- Changed state: **Discussion**

**Comment by GoogleCodeExporter** [comment]
```
на версии ebookdroid-1.4.2.apk тоже не открывает, в 
настройках не копался, изменений не вносил. 
почитав коменты от других прог, появилась 
идея, что не хватает оперативки, так как др. 
он открывает. 
будет ли это исправлено в следующей версии?
```

Original comment by `ed.v.he...@gmail.com` on 1 May 2012 at 5:11

**Comment by GoogleCodeExporter** [comment]
```
Посмотрите логи. Есть ли там outofmemory.

Надо будет подумать как можно сократить 
использование памяти. Попробуйте включить 
битмап хак в настройках.
```

Original comment by `Andrei.K...@gmail.com` on 1 May 2012 at 5:21

**Comment by GoogleCodeExporter** [comment]
```
вот логи, включением битмап хак ни чего не 
дало 
```

Original comment by `ed.v.he...@gmail.com` on 1 May 2012 at 6:26

Attachments:
- [alogcat.2012-05-01-22-21-53+0400.txt](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-4/alogcat.2012-05-01-22-21-53+0400.txt)

**Comment by GoogleCodeExporter** [comment]
```
Зобавно - тут надо смотреть реализацию.

D/skia    ( 3574): ------- skip threw an exception
W/System.err( 3574): java.io.IOException: Illegal seek
W/System.err( 3574):    at 
org.apache.harmony.luni.platform.OSFileSystem.seek(Native Method)
W/System.err( 3574):    at 
dalvik.system.BlockGuard$WrappedFileSystem.seek(BlockGuard.java:210)
W/System.err( 3574):    at java.io.FileInputStream.skip(FileInputStream.java:325)
W/System.err( 3574):    at 
java.io.BufferedInputStream.skip(BufferedInputStream.java:427)
W/System.err( 3574):    at 
android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err( 3574):    at 
android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:694)
W/System.err( 3574):    at 
org.ebookdroid.droids.cbx.codec.CbxPage.decode(CbxPage.java:59)
W/System.err( 3574):    at 
org.ebookdroid.droids.cbx.codec.CbxPage.renderBitmap(CbxPage.java:135)
W/System.err( 3574):    at 
org.ebookdroid.core.DecodeServiceBase.performDecode(DecodeServiceBase.java:187)
W/System.err( 3574):    at 
org.ebookdroid.core.DecodeServiceBase$DecodeTask.run(DecodeServiceBase.java:633)
W/System.err( 3574):    at 
org.ebookdroid.core.DecodeServiceBase$Executor.run(DecodeServiceBase.java:406)
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 1 May 2012 at 6:58

**Comment by GoogleCodeExporter** [comment]
```
 Интересный лог. Такого еще ни разу не видели. Будем думать. Нельзя ли пару слов про прошивку? Стоковая или какой-то кастом?
```

Original comment by `Andrei.K...@gmail.com` on 1 May 2012 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
прошивка Рутованная аналог официальных 
прошивок в виде .ZIP на Android 2.3.5 Gingerbread
```

Original comment by `ed.v.he...@gmail.com` on 1 May 2012 at 7:21

**Comment by GoogleCodeExporter** [comment]
```
сейчас попробую на samsung galaxy note
```

Original comment by `ed.v.he...@gmail.com` on 1 May 2012 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
тот же результат, также я попробовал 
перепаковать файл

W/System.err(23286):    at java.io.FileInputStream.skip(FileInputStream.java:325)
W/System.err(23286):    at 
java.io.BufferedInputStream.skip(BufferedInputStream.java:427)
W/System.err(23286):    at 
android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err(23286):    at 
android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:573)
W/System.err(23286):    at 
org.ebookdroid.droids.cbx.codec.CbxPage.decode(CbxPage.java:59)
W/System.err(23286):    at 
org.ebookdroid.droids.cbx.codec.CbxPage.renderBitmap(CbxPage.java:135)
W/System.err(23286):    at 
org.ebookdroid.core.DecodeServiceBase.performDecode(DecodeServiceBase.java:187)
W/System.err(23286):    at 
org.ebookdroid.core.DecodeServiceBase$DecodeTask.run(DecodeServiceBase.java:633)
W/System.err(23286):    at 
org.ebookdroid.core.DecodeServiceBase$Executor.run(DecodeServiceBase.java:406)
W/System.err(23286):    at java.lang.Thread.run(Thread.java:1019)
```

Original comment by `ed.v.he...@gmail.com` on 1 May 2012 at 7:34

Attachments:
- [Grimm_Fairy_Tales_Inferno_003_TriStan.cbr](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-9/Grimm_Fairy_Tales_Inferno_003_TriStan.cbr)

**Comment by GoogleCodeExporter** [comment]
```
А если в cbz перепаковать и попробовать?
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 1 May 2012 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
открылось без косяков и даже быстрее чем CBR 
раза в три-четыре )
но у меня 400GB манги и комиксов, 
переупаковывать я мягко говоря устану.
но все же спасибо за результат 
```

Original comment by `ed.v.he...@gmail.com` on 1 May 2012 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
а какие версии стоят - с маркета или 
скачанные?
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 1 May 2012 at 8:46

**Comment by GoogleCodeExporter** [comment]
```
с этого сайта скачанные 
```

Original comment by `ed.v.he...@gmail.com` on 1 May 2012 at 8:55

**Comment by GoogleCodeExporter** [comment]
```
Заметил одну общую черту у всех файлов на 
которые люди жалуются - пробелы в именах 
внутри архива. Интересно - не это ли 
вызывает проблемы и если да то почему не 
везде.
```

Original comment by `Andrei.K...@gmail.com` on 1 May 2012 at 10:23

**Comment by GoogleCodeExporter** [comment]
```
проверил эту теорию на "28 Days Later 01.cbr"
все файлы названы по порядку (Binder1_Page_01.jpg; 
Binder1_Page_02.jpg)
не открываются 1 и 8 страницы
```

Original comment by `ed.v.he...@gmail.com` on 1 May 2012 at 10:48

Attachments:
- [28 Days Later 01.cbr](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-15/28 Days Later 01.cbr)

**Comment by GoogleCodeExporter** [comment]
```
попробуйте вот это:
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 2 May 2012 at 8:34
- Changed state: **Started**

Attachments:
- [ebookdroid-1.4.3-dev-r1245.apk](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-16/ebookdroid-1.4.3-dev-r1245.apk)

**Comment by GoogleCodeExporter** [comment]
Original comment by `Alexander.V.Kasatkin@gmail.com` on 2 May 2012 at 8:36
- Added labels: **unrar**

**Comment by GoogleCodeExporter** [comment]
```
"28 Days Later 01.cbr" открыл очень быстро (как будто 
это был формат CBZ) и отображал все страницы, 
но с артефактами (только на некоторых 
рисунках), в виде синего прямоугольника в 
верхней левой части рисунка.
"Grimm_Fairy_Tales_Inferno_003_TriStan.cbr" открыл тоже очень 
быстро, но не все смог отобразить, большая 
часть это белые страницы, а те которые смог 
отобразить, были с артефактами. 
прикрепил весь лог, так как в начале открыл 
"28 Days Later 01.cbr" и затем "Grimm_Fairy_Tales_Inferno_003_TriStan.cbr"
и большое спасибо за оперативность 
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 10:40

Attachments:
- [alogcat.2012-05-02-14-30-46+0400.txt](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-18/alogcat.2012-05-02-14-30-46+0400.txt)

**Comment by GoogleCodeExporter** [comment]
```
Попробуйте еще раз, только перед этим 
сотрите кэш:
Menu->Clear Data->Delete all cached data from disk
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 2 May 2012 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
результат тот же
а вот по поводу артефактов, мне кажется это 
размер текстур отображается не корректно, 
128х128 он отображает как 128х64 (наверное 
поэтому Вы и попросили удалить кэш)
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 11:46

**Comment by GoogleCodeExporter** [comment]
```
А если так?
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 2 May 2012 at 12:17

Attachments:
- [ebookdroid-1.4.3-dev-r1246.apk](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-21/ebookdroid-1.4.3-dev-r1246.apk)

**Comment by GoogleCodeExporter** [comment]
```
1.4.3-dev-r1246 открыл и отобразил все картинки, а 
артефакты то появляются, то исчезают
они не зависят от скорости прокрутки или 
масштабирования
если несколько раз прокрутить на некоторое 
количество страниц, артефакты исчезают и 
больше не появляются  

```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 12:34

**Comment by GoogleCodeExporter** [comment]
```
По поводу артефактов - если Reuse bitmaps 
включено - что если отключить?
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 2 May 2012 at 12:57

**Comment by GoogleCodeExporter** [comment]
```
я не включал это меню после новой установки
перед каждой установкой я выбрал все 
пункты из Menu->Clear Data->
в управление приложениями чистил данные и 
кэш
после этого только удалял и не изменял ни 
каких настроек в проге 
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
/mnt/sdcard/.org.ebookdroid
эта папка у меня постоянна пуста
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
Ну это пока прога не упала:)
```

Original comment by `Andrei.K...@gmail.com` on 2 May 2012 at 1:18

**Comment by GoogleCodeExporter** [comment]
```
нет, нормально работает )
вчера ночью, все что было на телефоне 
перевел в CBZ с помощью PowerArchiver
(у нее есть функция "преобразовать")
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:27

**Comment by GoogleCodeExporter** [comment]
```
но оставил несколько CBR для теста
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:28

**Comment by GoogleCodeExporter** [comment]
```
нашел еще один баг, если на телефоне пару 
десятков манг, то до листать в режиме полка 
не возможна, прога просто крошиться 
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:40

**Comment by GoogleCodeExporter** [comment]
```
вот логи
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:41

Attachments:
- [alogcat.2012-05-02-17-37-40+0400.txt](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-30/alogcat.2012-05-02-17-37-40+0400.txt)

**Comment by GoogleCodeExporter** [comment]
```
сейчас протестил манхву, он ее не может 
отобразить (белый лист с номером страницы)
хотя в режиме полка он показывает обложку 
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:51

Attachments:
- [Trace_v01_!Intro[RSC].cbz](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-31/Trace_v01_!Intro[RSC].cbz)

**Comment by GoogleCodeExporter** [comment]
```
вот другой пример
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:53

Attachments:
- [Wake_Up_Deadman_ch001[RSC].cbr](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-32/Wake_Up_Deadman_ch001[RSC].cbr)

**Comment by GoogleCodeExporter** [comment]
```
а вот и логи
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 1:54

Attachments:
- [alogcat.2012-05-02-17-51-25+0400.txt](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-33/alogcat.2012-05-02-17-51-25+0400.txt)

**Comment by GoogleCodeExporter** [comment]
```
Мда. Судя по логам феерически не хватает 
памяти. Ладно, подумаем, как можно обойти 
это дело.
```

Original comment by `Andrei.K...@gmail.com` on 2 May 2012 at 1:59

**Comment by GoogleCodeExporter** [comment]
```
Вы свойства картинок видели? по 7000 
пикселей! Первый раз вижу мангу в рулоне:)

На данном этапе развития EBookDroid мало что 
можно сделать. Но могу обрадовать: Android 4.0 
вам поможет.
```

Original comment by `Andrei.K...@gmail.com` on 2 May 2012 at 2:36

**Comment by GoogleCodeExporter** [comment]
```
это вэб-манхва, она так и идет в рулонах )
ни один из просмотрщиков манги не 
отображает ее корректно 
а можете рассказать как Android 4.0 поможет? 
```

Original comment by `ed.v.he...@gmail.com` on 2 May 2012 at 6:49

**Comment by GoogleCodeExporter** [comment]
```
На 2.3.5 размер памяти доступный приложению 
сильно ограничен системой. В вашем случае - 
32 мегабайта. А всего лишь один лист в ваших 
примерах требует почти 16. Без учета 
остальных нужд читалки.
Под 4.0 программы могут использовать до 256 
мегабайт памяти в джаве и сколько загребут 
в нативной части.
```

Original comment by `Andrei.K...@gmail.com` on 3 May 2012 at 6:22

**Comment by GoogleCodeExporter** [comment]
```
спасибо за ответ, теперь буду ждать 4.0 )
```

Original comment by `ed.v.he...@gmail.com` on 3 May 2012 at 5:02

**Comment by GoogleCodeExporter** [comment]
Original comment by `Andrei.K...@gmail.com` on 4 May 2012 at 7:58
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
Вот еще одну версию попробуйте.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 18 May 2012 at 1:11

Attachments:
- [ebookdroid-1.4.3-dev-r1286.apk](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-40/ebookdroid-1.4.3-dev-r1286.apk)

**Comment by GoogleCodeExporter** [comment]
```
результат тот же, при перелистывании полки 
рухнула и манхву не открыла
на всякий случай логи
```

Original comment by `ed.v.he...@gmail.com` on 18 May 2012 at 1:37

Attachments:
- [alogcat.2012-05-18-17-34-05+0400.txt](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-221/comment-41/alogcat.2012-05-18-17-34-05+0400.txt)

**Comment by GoogleCodeExporter** [comment]
```
В вашем случае поможет только 4ый андроид.
```

Original comment by `Andrei.K...@gmail.com` on 18 May 2012 at 2:45

**Comment by GoogleCodeExporter** [comment]
```
спасибо, как выйдет 4ый андроид, отпишусь с 
результатами 
```

Original comment by `ed.v.he...@gmail.com` on 18 May 2012 at 2:59
