### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JustLoy77/ebookdroid#769]
```
What steps will reproduce the problem?
1.Open the app
2. Go to main screen
3.Open the app again

What is the expected output?
bring the app back to foreground


What do you see instead?
Application Error
An unexpected error has occured
Only the original thread that created a view hierarchy can touch its views.

and then crashes

What version of the product are you using?
v2.1.8

On what operating system?
Android 4.0.4

What device are you using?
Samsung Galaxy Tab GT-P7500

Please provide any additional information below.

```

Original issue reported on code.google.com by `alves...@gmail.com` on 9 Apr 2014 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
Can you please attach crash dump from /sdcard/.org.ebookdroid/logs ?
```

Original comment by `Andrei.K...@gmail.com` on 9 Apr 2014 at 6:51

**Comment by GoogleCodeExporter** [comment]
```
org.ebookdroid.2.1.8.20140403.111505.stacktrace 

Application information:

This file was generated by the org.ebookdroid.2.1.8(218001)

Device information:

VERSION     : 15
BOARD       : GT-P7500
BRAND       : samsung
CPU_ABI     : armeabi-v7a
CPU_ABI2    : armeabi
DEVICE      : GT-P7500
DISPLAY     : IMM76D.XWLP9
FINGERPRINT : samsung/GT-P7500/GT-P7500:4.0.4/IMM76D/XWLP9:user/release-keys
ID          : IMM76D
MANUFACTURER: samsung
MODEL       : GT-P7500
PRODUCT     : GT-P7500

Error information:

java.lang.RuntimeException: cannot load document 
'/mnt/sdcard/Livros/RED/Calculo/Cálculo diferencial e integral_Paulo 
Boulos.pdf'
    at org.ebookdroid.droids.mupdf.MuPdfDroid.nativeOpen(Native Method)
    at org.ebookdroid.droids.mupdf.MuPdfDroid.The(SourceFile:41)
    at org.ebookdroid.droids.base.impl.AbstractNativeDroid.version(SourceFile:65)
    at zb.Since(SourceFile:60)
    at xf.Since(SourceFile:69)
    at anz.version(SourceFile:995)
    at anz.Since(SourceFile:1)
    at jt.call(SourceFile:215)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
```

Original comment by `alves...@gmail.com` on 10 Apr 2014 at 1:46

**Comment by GoogleCodeExporter** [comment]
```
Thank you. But it seems to be different crash: as you can see error message is 
different.

Does your reported error occurs every time when you go to main screen and 
opening app again? I can not reproduce this error on my devices.
```

Original comment by `Andrei.K...@gmail.com` on 10 Apr 2014 at 3:20
- Changed state: **Discussion**

**Comment by GoogleCodeExporter** [comment]
```
I realized its a differente error, but its the only file in the directory...

I'm uploading a video with the error...
```

Original comment by `alves...@gmail.com` on 10 Apr 2014 at 4:58

Attachments:
- [crash.mp4](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-769/comment-4/crash.mp4)

**Comment by GoogleCodeExporter** [comment]
```
OK. Thank you. We will try to reproduce and fix this ASAP.
```

Original comment by `Andrei.K...@gmail.com` on 11 Apr 2014 at 7:11

**Comment by GoogleCodeExporter** [comment]
```
I am have also been getting this error daily since ebookdroid 2.1.8.  Currently 
running 2.1.9 on android 4.4.4 on a Nexus 4. It does not create an error in 
their .org.ebookdroid/logs directory.

Steps to reproduce ( at least it happens daily for me )
1. Open a large pdf (12.7 mb is the size  PDF I've been reading)
2. After opening and reading a few pages press the home button
3. Star using the phone normally for email games browsing the web etc
4. Reopen ebookdeoid several hours later to resume reading PDF and it throws 
the error and closes the current PDF and returns toy to the library page

Hope you are able to track down this bug! Thanks for a great app

```

Original comment by `chrisj...@gmail.com` on 13 Jul 2014 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
I am also getting this error on a daily basis.  No crash logs are produced.  I 
am reading a 6MB .PDF file.  I think the error occurs after ebookdroid has been 
swapped out of memory due to another app needing lots of RAM.
```

Original comment by `morrinm...@gmail.com` on 4 Jan 2015 at 12:37
