### ISSUE TITLE
object not locked by thread before wait()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JustLoy77/ebookdroid#853]
```
What steps will reproduce the problem?
1.After app has been unused for a time, reopening app to read PDF file,triggers 
thread lock error when opening app.
2.The error cannot be triggered at will but has occurred at least four times 
today.
3.App must be closed and reopened to clear error.

What is the expected output?
Continue reading PDF from point where stopped reading.

What do you see instead?
Object not locked by thread before wait()

What version of the product are you using?
2.1.12

On what operating system?
Android 4.1.2

What device are you using?
Samsung tab 3

Please provide any additional information below.

```

Original issue reported on code.google.com by `Morse.Da...@gmail.com` on 2 Sep 2014 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
Issue 854 has been merged into this issue.
```

Original comment by `Andrei.K...@gmail.com` on 2 Sep 2014 at 9:16

**Comment by GoogleCodeExporter** [comment]
```
Confirmed for Xperia L
Android 4.2.2
Latest version of app at this moment
```

Original comment by `istand...@gmail.com` on 7 Sep 2014 at 7:09

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue with oneplus one, android 4.4.4, CyanogenMod 11s


```

Original comment by `rlevi...@gmail.com` on 9 Sep 2014 at 1:41

**Comment by GoogleCodeExporter** [comment]
```
Samsung Galaxy Note 10.1, Android 4.1.2, ebookdroid 2.1.12.

I had one file in the ebookdroid library that was also on Dropbox.

1. Long press the file's entry in the ebookdroid library 
2. Tap "file operations." 
3. Tap "delete book." 
4. Tap "ok." 

Ebookdroid now loads without problems. I have had no recurrence the past few 
days, though it had been occurring multiple times a day since about the time my 
Dropbox client started using is own previewer for PDFs. I viewed the file on 
ebookdroid again this morning, and the issue returned. 
```

Original comment by `caffeine...@gmail.com` on 11 Sep 2014 at 1:56

**Comment by GoogleCodeExporter** [comment]
```
It is very very strange behaviour. I think it is a coincidence. Dropbox or any 
other software should not affect ebookdroid.
```

Original comment by `Andrei.K...@gmail.com` on 11 Sep 2014 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
but andrid can close o change apps, this can afect, example
the first intance open a book
another app charge and android close the first instance
the second instance find a flag from first instance and throws message error 
with button (Close)

Sorry for mi inglish
```

Original comment by `ociomast...@gmail.com` on 11 Sep 2014 at 2:31

**Comment by GoogleCodeExporter** [comment]
```
Can you attack or upload somewhere logs for this crash from 
/sdcard/.org.ebookdroid/logs/ ?
```

Original comment by `Andrei.K...@gmail.com` on 11 Sep 2014 at 2:46

**Comment by GoogleCodeExporter** [comment]
```
Issue 860 has been merged into this issue.
```

Original comment by `Andrei.K...@gmail.com` on 11 Sep 2014 at 2:48

**Comment by GoogleCodeExporter** [comment]
```
Wehre  the atack button?


Application information:

This file was generated by the org.ebookdroid.2.1.9(219001)

Device information:

VERSION     : 16
BOARD       : MSM8960
BRAND       : Sony
CPU_ABI     : armeabi-v7a
CPU_ABI2    : armeabi
DEVICE      : LT30p
DISPLAY     : 9.1.A.1.141
FINGERPRINT : 
Sony/LT30p_1265-1632/LT30p:4.1.2/9.1.A.1.141/cvt_tw:user/release-keys
ID          : 9.1.A.1.141
MANUFACTURER: Sony
MODEL       : LT30p
PRODUCT     : LT30p_1265-1632

Error information:

javax.net.ssl.SSLHandshakeException: 
java.security.cert.CertPathValidatorException: Trust anchor for certification 
path not found.
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)
    at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
    at libcore.net.http.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:130)
    at java.net.URLConnection.getContentType(URLConnection.java:326)
    at libcore.net.http.HttpsURLConnectionImpl.getContentType(HttpsURLConnectionImpl.java:196)
    at gi.Since(SourceFile:33)
    at ge.Since(SourceFile:26)
    at aev.Since(SourceFile:175)
    at ady.version(SourceFile:998)
    at ady.Since(SourceFile:1)
    at l.call(SourceFile:215)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
Caused by: java.security.cert.CertificateException: 
java.security.cert.CertPathValidatorException: Trust anchor for certification 
path not found.
    at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:192)
    at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:573)
    at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
    at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
    at libcore.net.http.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:130)
    at java.net.URLConnection.getContentType(URLConnection.java:326)
    at libcore.net.http.HttpsURLConnectionImpl.getContentType(HttpsURLConnectionImpl.java:196)
    at gi.Since(SourceFile:33)
    at ge.Since(SourceFile:26)
    at aev.Since(SourceFile:175)
    at ady.version(SourceFile:998)
    at ady.Since(SourceFile:1)
    at l.call(SourceFile:215)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for 
certification path not found.
    at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:192)
    at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:573)
    at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
    at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
    at libcore.net.http.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:130)
    at java.net.URLConnection.getContentType(URLConnection.java:326)
    at libcore.net.http.HttpsURLConnectionImpl.getContentType(HttpsURLConnectionImpl.java:196)
    at gi.Since(SourceFile:33)
    at ge.Since(SourceFile:26)
    at aev.Since(SourceFile:175)
    at ady.version(SourceFile:998)
    at ady.Since(SourceFile:1)
    at l.call(SourceFile:215)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for 
certification path not found.
    at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:192)
    at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:573)
    at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
    at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
    at libcore.net.http.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:130)
    at java.net.URLConnection.getContentType(URLConnection.java:326)
    at libcore.net.http.HttpsURLConnectionImpl.getContentType(HttpsURLConnectionImpl.java:196)
    at gi.Since(SourceFile:33)
    at ge.Since(SourceFile:26)
    at aev.Since(SourceFile:175)
    at ady.version(SourceFile:998)
    at ady.Since(SourceFile:1)
    at l.call(SourceFile:215)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)

```

Original comment by `ociomast...@gmail.com` on 11 Sep 2014 at 2:59

**Comment by GoogleCodeExporter** [comment]
```
another atach 

Application information:

This file was generated by the org.ebookdroid.2.1.10(219301)

Device information:

VERSION     : 16
BOARD       : MSM8960
BRAND       : Sony
CPU_ABI     : armeabi-v7a
CPU_ABI2    : armeabi
DEVICE      : LT30p
DISPLAY     : 9.1.A.1.141
FINGERPRINT : 
Sony/LT30p_1265-1632/LT30p:4.1.2/9.1.A.1.141/cvt_tw:user/release-keys
ID          : 9.1.A.1.141
MANUFACTURER: Sony
MODEL       : LT30p
PRODUCT     : LT30p_1265-1632

Error information:

java.lang.SecurityException: Permission Denial: opening provider 
com.google.android.gm.provider.MailProvider from ProcessRecord{421a54c0 
1709:org.ebookdroid/u0a201} (pid=1709, uid=10201) requires 
com.google.android.gm.permission.READ_GMAIL or 
com.google.android.gm.permission.WRITE_GMAIL
    at android.os.Parcel.readException(Parcel.java:1425)
    at android.os.Parcel.readException(Parcel.java:1379)
    at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2354)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:4261)
    at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:1744)
    at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1099)
    at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:706)
    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:612)
    at android.content.ContentResolver.openInputStream(ContentResolver.java:447)
    at Local.Since(SourceFile:122)
    at gs.Since(SourceFile:23)
    at gr.Since(SourceFile:26)
    at afp.Since(SourceFile:175)
    at aer.version(SourceFile:1017)
    at aer.Since(SourceFile:1)
    at r.call(SourceFile:215)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
```

Original comment by `ociomast...@gmail.com` on 11 Sep 2014 at 3:00

**Comment by GoogleCodeExporter** [comment]
```
It seems to be 2 different issues, not related to current. Thank you for logs. 
I will investigate.
```

Original comment by `Andrei.K...@gmail.com` on 11 Sep 2014 at 5:28

**Comment by GoogleCodeExporter** [comment]
```
I have screenshots
```

Original comment by `ociomast...@gmail.com` on 11 Sep 2014 at 5:57

**Comment by GoogleCodeExporter** [comment]
```
Nook HD+ expierences same issue.
Nook version 2.2 unkown android version
Steps to reproduce
Open book in ebookpub.
Turn wifi on.
Open browser.
Turn wifi off.
Go backto ebookpub.  Error happens everytime.
```

Original comment by `rmeredi...@msn.com` on 13 Sep 2014 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
I see the same issue on the Nexus 10, Galaxy Tab Pro 12.2, and Tab Pro 8.4 
running CyanogenMod.

Incidentally, if you just hit the back button instead of pressing close you can 
ignore the error message instead of losing your place, but it still pops up 
very frequently and is annoying.
```

Original comment by `randbrit...@gmail.com` on 13 Sep 2014 at 11:46

**Comment by GoogleCodeExporter** [comment]
```
Confirmed on Nexus 10 with Android 4.4.4, ebookdroid 2.1.12
```

Original comment by `dev.cl...@gmail.com` on 20 Sep 2014 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
Issue 861 has been merged into this issue.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 20 Sep 2014 at 8:10

**Comment by GoogleCodeExporter** [comment]
```
Issue 861 has been merged into this issue.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 23 Sep 2014 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
Issue 860 has been merged into this issue.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 23 Sep 2014 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
Issue 854 has been merged into this issue.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 23 Sep 2014 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
Try this version:
https://drive.google.com/file/d/0B6DTNNagrvFPZk9DZ1ZaVkFLTnc
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 23 Sep 2014 at 8:39

**Comment by GoogleCodeExporter** [comment]
```
Issue 869 has been merged into this issue.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 24 Sep 2014 at 3:34

**Comment by GoogleCodeExporter** [comment]
```
Issue 868 has been merged into this issue.
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 24 Sep 2014 at 10:54

**Comment by GoogleCodeExporter** [comment]
```
This version doesn't seem to be throwing up the error anymore, although it does 
reload the whole document after being kept in the background for a 
comparatively short time.
```

Original comment by `randbrit...@gmail.com` on 24 Sep 2014 at 1:17

**Comment by GoogleCodeExporter** [comment]
```
Re #23: 
what version?

Re #4:
The instructions I wrote were instructions for removing a book from "recents." 
The error is occurring now, though, so I guess it must have been a coincidence. 
For some reason, the latest log I have is from last month. Here it is FWIW.


Application information:

This file was generated by the org.ebookdroid.2.1.12(219371)

Device information:

VERSION     : 16
BOARD       : smdk4x12
BRAND       : samsung
CPU_ABI     : armeabi-v7a
CPU_ABI2    : armeabi
DEVICE      : p4notewifi
DISPLAY     : JZO54K.N8013UEUCMI3
FINGERPRINT : 
samsung/p4notewifiue/p4notewifi:4.1.2/JZO54K/N8013UEUCMI3:user/release-keys
ID          : JZO54K
MANUFACTURER: samsung
MODEL       : GT-N8013
PRODUCT     : p4notewifiue

Error information:

java.lang.SecurityException: Permission Denial: opening provider 
com.google.android.gm.provider.MailProvider from ProcessRecord{43869e80 
23581:org.ebookdroid/u0a203} (pid=23581, uid=10203) requires 
com.google.android.gm.permission.READ_GMAIL or 
com.google.android.gm.permission.WRITE_GMAIL
    at android.os.Parcel.readException(Parcel.java:1425)
    at android.os.Parcel.readException(Parcel.java:1379)
    at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2541)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:4319)
    at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:1952)
    at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1101)
    at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:708)
    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:614)
    at android.content.ContentResolver.openInputStream(ContentResolver.java:449)
    at Partial.Since(SourceFile:122)
    at gn.Since(SourceFile:23)
    at gm.Since(SourceFile:26)
    at afn.Since(SourceFile:209)
    at aep.Since(SourceFile:1035)
    at aep.The(SourceFile:1)
    at n.call(SourceFile:243)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)

```

Original comment by `caffeine...@gmail.com` on 24 Sep 2014 at 4:53

**Comment by GoogleCodeExporter** [comment]
```
#24: the version linked in post #20.
```

Original comment by `randbrit...@gmail.com` on 24 Sep 2014 at 5:32

**Comment by GoogleCodeExporter** [comment]
```
# 20 that version has worked for me ( so far )
```

Original comment by `silentso...@googlemail.com` on 25 Sep 2014 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
Issue 870 has been merged into this issue.
```

Original comment by `Andrei.K...@gmail.com` on 25 Sep 2014 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
Спасибо, версия 2.1.13 работает стабильно

24.09.2014 17:55 пользователь <ebookdroid@googlecode.com> 
написал:

locked by thread before wait()
```

Original comment by `bvg...@gmail.com` on 26 Sep 2014 at 5:28

**Comment by GoogleCodeExporter** [comment]
```
Can confirm that this issue also has been present on Kindle Fire HD 7" running 
KindleOS (based on Android 4.0.3) but release 2.1.13-dev-r4266 fixed it as 
indicated above.

The issue occurred when trying to open a file residing in a Seafile cache (file 
sync solution similar to Dropbox but open source).
```

Original comment by `monochro...@gmail.com` on 7 Oct 2014 at 4:00

**Comment by GoogleCodeExporter** [comment]
```
Issue 875 has been merged into this issue.
```

Original comment by `Andrei.K...@gmail.com` on 9 Oct 2014 at 8:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `Alexander.V.Kasatkin@gmail.com` on 14 Oct 2014 at 3:32
- Changed state: **Fixed**
