### ISSUE TITLE
Crash when loading a doc after highlight

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JustLoy77/ebookdroid#866]
```
What steps will reproduce the problem?
1. Highlight heavily a pdf or djvu 
2. Loading time of the doc is greater as you highlight more and more
3. Until finally stops loading and says Application cannot create bitmap buffer

here is the log:

Application information:

This file was generated by the org.ebookdroid.2.1.12(219371)

Device information:

VERSION     : 19
BOARD       : universal5420
BRAND       : samsung
CPU_ABI     : armeabi-v7a
CPU_ABI2    : armeabi
DEVICE      : lt03wifiue
DISPLAY     : KOT49H.P600UEUCNI1
FINGERPRINT : 
samsung/lt03wifiue/lt03wifiue:4.4.2/KOT49H/P600UEUCNI1:user/release-keys
ID          : KOT49H
MANUFACTURER: samsung
MODEL       : SM-P600
PRODUCT     : lt03wifiue

Error information:

java.lang.OutOfMemoryError: Application cannot create bitmap buffer
    at org.ebookdroid.common.bitmaps.ByteBufferBitmap.<init>(SourceFile:57)
    at fu.Since(SourceFile:24)
    at org.ebookdroid.common.bitmaps.ByteBufferBitmap.Since(SourceFile:114)
    at lu.version(SourceFile:298)
    at lu.Since(SourceFile:270)
    at ne.Since(SourceFile:53)
    at nc.Since(SourceFile:245)
    at lb.Since(SourceFile:163)
    at aep.Since(SourceFile:1044)
    at aep.The(SourceFile:1)
    at n.call(SourceFile:243)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)


What version of the product are you using?
2.1.12

On what operating system?
4.4.2

What device are you using?
Galaxy note 10.1 v2014

Please provide any additional information below.

```

Original issue reported on code.google.com by `gst...@gmail.com` on 22 Sep 2014 at 4:18

**Comment by GoogleCodeExporter** [comment]
```
How many pages are cached in memory ?
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 22 Sep 2014 at 4:27
- Changed state: **Discussion**

**Comment by GoogleCodeExporter** [comment]
```
Just 2.
```

Original comment by `gst...@gmail.com` on 22 Sep 2014 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
Can you please export you drawings (from bookshelf) and upload them with your 
document somewhere?
```

Original comment by `Andrei.K...@gmail.com` on 22 Sep 2014 at 8:56

**Comment by GoogleCodeExporter** [comment]
```
If I understand what you ask me I already did it, what I did was to save 
annotations from bookshelf, rightclicking the document, I saw that it creates a 
file *.eaz that gets bigger as I highlight more and more. After throwing the 
error I clear cache, and the document opens normally again, after that restore 
annotations (but from bookshelf, not when the document is already open,I dont 
know how to do that if its posible), then again gives error.
I'll tell you how to reproduce the error, its easy, just highlight pages fully, 
it takes no more than 5 or 6 pages, close the document, open another, close it, 
and reopen the highlighted one, there you have the error. Hope that it helps 
you.
```

Original comment by `gst...@gmail.com` on 23 Sep 2014 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Here you have the book and annotations

http://www.adrive.com/public/K4CmGx/Geometrical_methods_of_mathematical-Schutz.d
jvu
http://www.adrive.com/public/d7bnJE/Geometrical_methods_of_mathematical-Schutz.e
az



```

Original comment by `gst...@gmail.com` on 23 Sep 2014 at 5:30

**Comment by GoogleCodeExporter** [comment]
```
Thank you. I found bug. Fix will be available in next version.
```

Original comment by `Andrei.K...@gmail.com` on 23 Sep 2014 at 6:00
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Great. Thank YOU for your great app. Looking forward to the next version.
```

Original comment by `gst...@gmail.com` on 23 Sep 2014 at 6:14

**Comment by GoogleCodeExporter** [comment]
```
Try this version:
https://drive.google.com/file/d/0B6DTNNagrvFPZk9DZ1ZaVkFLTnc
```

Original comment by `Alexander.V.Kasatkin@gmail.com` on 23 Sep 2014 at 8:38
