### ISSUE TITLE
NullPointerException at org.ebookdroid.core.PageTreeNode$2.run(PageTreeNode.java:223)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JustLoy77/ebookdroid#88]
```
Происходит аварийное завершение 
приложения с исключением NullPointerException at 
org.ebookdroid.core.PageTreeNode$2.run(PageTreeNode.java:223), revision 582 
(версия 1.3).
В строке 223 PageTreeNode.java оказывается, что 
bitmapBounds==null.
Патч в аттаче позволяет обойти проблему, 
но, по всей видимости, она где-то глубже.
Еще иногда происходит NullPointerException
    at org.ebookdroid.core.PageTreeNode.calculateAvgLum(PageTreeNode.java:340)

PS Очень понравился кроппинг, поэтому 
остался на текущей ревизии, несмотря на 
ошибки.
```

Original issue reported on code.google.com by `mindphaser2k6` on 8 Nov 2011 at 8:44

Attachments:
- [org.ebookdroid.1.3.0-dev.20111108.222541.stacktrace](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-88/comment-0/org.ebookdroid.1.3.0-dev.20111108.222541.stacktrace)
- [PageTreeNode.java.patch](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-88/comment-0/PageTreeNode.java.patch)

**Comment by GoogleCodeExporter** [comment]
```
Похоже, баг возникает при использовании 
кэширования (страниц в памяти=3). Если 
поставить 0, то нет.
```

Original comment by `mindphaser2k6` on 9 Nov 2011 at 4:00

**Comment by GoogleCodeExporter** [comment]
```
Баг точно глубже. Там где падает сейчас 
нулл из-за того, что декодирование страницы 
было неуспешным. Возможно не хватило 
памяти. Надо проверить, что все выделенные 
битмапы освобождаются.
```

Original comment by `Andrei.K...@gmail.com` on 9 Nov 2011 at 7:57

**Comment by GoogleCodeExporter** [comment]
```
Вполне возможно, что из-за памяти, т.к. даже 
если поставить nullcheck, часть страниц не 
отображается, а иногда программа падает с 
OutOfMemoryError.
```

Original comment by `mindphaser2k6` on 9 Nov 2011 at 8:31

Attachments:
- [org.ebookdroid.1.3.0-dev.20111109.081221.stacktrace](https://storage.googleapis.com/google-code-attachments/ebookdroid/issue-88/comment-3/org.ebookdroid.1.3.0-dev.20111109.081221.stacktrace)

**Comment by GoogleCodeExporter** [comment]
```
Попробуй ревизию 586 - должно стать полегче.
```

Original comment by `Andrei.K...@gmail.com` on 10 Nov 2011 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
Действительно, стало намного лучше. Пока 
багов не наблюдаю. Еще потестирую, если что 
проявится - напишу.
```

Original comment by `mindphaser2k6` on 10 Nov 2011 at 3:55

**Comment by GoogleCodeExporter** [comment]
Original comment by `Andrei.K...@gmail.com` on 26 Nov 2011 at 10:21
- Changed state: **Fixed**
