### ISSUE TITLE
Export book annotations doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JustLoy77/ebookdroid#944]
```
What steps will reproduce the problem?
1. Take scanned djvu document (in my case it's about 300+ pages)
2. Make some underlines with drawing tools (I read about 70 pages, drawings are 
on half of them)
3. Run "export" command

What is the expected output?
Epub file with drawings/annotations

What do you see instead?
The app hangs for several minutes and crashes. Below is the log file.

This file was generated by the org.pdf.and.djvu.reader.2.2.4(224001)
Device information:

VERSION     : 19
BOARD       : universal5420
BRAND       : samsung
CPU_ABI     : armeabi-v7a
CPU_ABI2    : armeabi
DEVICE      : v1awifi
DISPLAY     : KOT49H.P900UEU1BNK1
FINGERPRINT : 
samsung/v1awifiue/v1awifi:4.4.2/KOT49H/P900UEU1BNK1:user/release-keys
ID          : KOT49H
MANUFACTURER: samsung
MODEL       : SM-P900
PRODUCT     : v1awifiue

Error information:

java.lang.RuntimeException: An error occured while executing doInBackground()
    at jc.done(SourceFile:256)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.OutOfMemoryError
    at android.graphics.Bitmap.nativeCreate(Native Method)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
    at rv.Since(SourceFile:140)
    at arm.Since(SourceFile:265)
    at arm.and(SourceFile:246)
    at arm.Since(SourceFile:60)
    at arp.version(SourceFile:374)
    at jm.Since(SourceFile:21)
    at jm.The(SourceFile:1)
    at jb.call(SourceFile:243)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

What version of the product are you using?
2.2.4

On what operating system?
KitKat

What device are you using?
Samsung NotePro
```

Original issue reported on code.google.com by `Bvo...@gmail.com` on 21 May 2015 at 4:30

**Comment by GoogleCodeExporter** [comment]
```
PS: when I read about 10 pages export worked without problems.
```

Original comment by `Bvo...@gmail.com` on 21 May 2015 at 4:36

**Comment by GoogleCodeExporter** [comment]
```
Confirmed. Will be fixed in next release, I hope.
```

Original comment by `Andrei.K...@gmail.com` on 21 May 2015 at 5:54
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Fixed.
```

Original comment by `Andrei.K...@gmail.com` on 22 May 2015 at 8:15
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
It works, but I don't sure if the result is as expected.
I've got scanned (not OCR) document with 300+ pages ~60Mb.
After 10 mins of export the app creates epub with 30 pages ~250Mb(!).
But the epub has blank pages with pages from source on top half of resulting 
pages as pictures. As epub has no crop futures it's very hard to read small 
pictures - only zooming on every page can help.
As I remember earlier export copied pages from source to resulting epub as 
pictures, expanded to a full page view.
```

Original comment by `Bvo...@gmail.com` on 21 Jun 2015 at 10:42
